Repository Akshat111111/NexTrade, pull requests merged in 2024-10, with the labels that each got.

#28 LICENSE FILE ADDED
  LICENSE
  README.md
Labels: wob24, Level 1

#40 Add Toggle Dark Mode Button with Attractive Icons
  templates/index.html
Labels: wob24, Level 2

#38 multi language support added
  templates/index.html
Labels: wob24, Level 2

#46 Update README.md
  README.md
Labels: wob24, Level 1

#48 Update CONTACT SECTION in Readme.md
  README.md
Labels: wob24, Level 1

#51 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: wob24, Level 1

#49 Update CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: wob24, Level 1, hacktoberfest -accepted, gssoc-ext

#53 Added logo and reviewed changes
  templates/index.html
  templates/nex.webp
Labels: wob24, Level 1

#58 Added Greetings on issues and pull requests
  .github/workflows/greetings.yml
Labels: wob24, Level 1, gssoc-ext

#67 ✨Add Visitor Counter feature done ! #59
  templates/index.html
  templates/visi.css
  templates/visi.js
Labels: wob24, hacktoberfest -accepted, gssoc-ext

#64 Updated Scroll Button Functionality
  templates/index.html
Labels: wob24, Level 2, gssoc-ext
