Repository Akshat111111/NexTrade, pull requests merged in 2024-11, with the labels that each got.

#74 Main
  templates/index.html
Labels: wob24, Level 1, gssoc-ext

#86 Add Stargazers and Forkers to READMEmd ✨
  README.md
Labels: wob24, Level 1, gssoc-ext

#78 Add a new page to display all contributors done ! #61 ✨
  templates/contributors.css
  templates/contributors.html
  templates/contributors.js
  templates/index.html
Labels: wob24, Level 3, gssoc-ext

#89 Added Copyright at footer and Terms of Service page
  templates/index.html
  templates/terms.html
  templates/visi.js
Labels: wob24, Level 2, gssoc-ext

#79 Update Readme.md added Fundamentals of Blockchain and Ethereum
  README.md
  howdoesethereumwork.pdf
Labels: wob24, Level 2, gssoc-ext

#94 Add Feedback/Rate Us page done ! #63
  templates/contributors.html
  templates/feedback.html
  templates/index.html
  templates/styles.css
Labels: wob24, Level 3, gssoc-ext

#93 Fixed homepage visitor counter to track unique visits only once per user session
  templates/visi.js
Labels: wob24, Level 2, gssoc-ext

#95 ADD CICD Workflows for GITHUB Automation
  .github/workflows/auto-comment-issues.yml
  .github/workflows/auto-comment-prs.yml
  .github/workflows/close-issues-on-pr-merge.yml
  .github/workflows/comment-on-issue-close.yml
  .github/workflows/comment-on-pr-merge.yml
  .github/workflows/label-issues-prs.yml
Labels: wob24, Level 2, gssoc-ext

#119 Implement Auto-Labeling Workflow for GitHub
  .github/workflows/auto-label.yml
Labels: wob24, Level 1, gssoc-ext

#112 Add Footer done ! #103
  templates/index.html
  templates/visi.css
Labels: wob24, Level 2, gssoc-ext

#111 Add Header done ! #102
  templates/index.html
Labels: wob24, Level 2, gssoc-ext

#110 Add Edit Profile Feature in Profile Page done ! #99 🟢
  templates/index.html
  templates/profile.html
  templates/profileedit.html
  templates/testp.js
Labels: wob24, Level 3, gssoc-ext

#108 Add Project Statistics in Contributors page done ! #100
  templates/contributors.css
  templates/contributors.html
Labels: wob24, Level 2, gssoc-ext

#118 Add Signup/Register page done ! #117 🟢🟢
  templates/index.html
  templates/signup.css
  templates/signup.html
Labels: wob24, Level 2, gssoc-ext

#114 Add a pop up dialog box for subscribing to newsletter done ! #105
  templates/index.html
  templates/newsletterpopup.jpg
  templates/newsletterpopup.js
Labels: wob24, Level 3, gssoc-ext

#121 Handling 404 error page (fixing Issue no: 116)
  app/routes.py
  templates/error_404.html
Labels: wob24, Level 2, gssoc-ext
